services:
  db:
    image: psql
    container_name: psql
    environment:
      POSTGRES_PASSWORD: leffe
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    network_mode: "host"
    restart: unless-stopped

  backend:
    image: tomcat
    container_name: tomcat
    ports:
      - 8443:8443
      - 8080:8080
    network_mode: "host"  
    restart: unless-stopped

  web:
    image: nginx
    container_name: nginx
    ports:
      - 443:443
    network_mode: "host"
    restart: unless-stopped